### ISSUE TITLE
Reducing background noise

### ISSUE THREAD

**Issue by ghost** [zeekoe/MICGAIN-s5neolte#3]
Hi there! Thank you so much for creating this mod! Calling is possible again on my SM-G903F running the last official LineageOS 17.1 release (Android 10, 13.02.22) :medal_sports: 

However, it also drastically increases the volume of any background noise (cars, trains, conversations). Therefore, calling is currently only possible in very quiet environments. Is there anything one can actually do to make the effect a little more selective? :)

**Comment by zeekoe** [comment]
Haha, nice!
You could try reducing the volume. I don't have an S5 Neo anymore, so can't test it, so sorry I can't be of much help I think...

**Comment by ghost** [comment]
Oh no! I'm thinking about replacing it too, but it's so hard to find one with replaceable battery these days.

This means editing the mixer_paths_0.xml, right? Which value(s)? And could I just edit the zip, and re-run the update? :)

**Comment by zeekoe** [comment]
I'm happily using an LG G5 since quite a while now. It has replaceable everything. But LG quit their unlocking service, so you're stuck at stock Android unless you buy an already unlocked one. And of course there's the Fairphone 3/4.

But it would be even better if you could keep using yours. :) Indeed editing the mixer_paths file should do the trick. You could compare it (with a diff tool, for example kdiff3) to the original that LineageOS provides, to see what values I edited. I remember it's a mess: for every network type there is a separate setting. And indeed, editing the zip and re-running the update should work. I created a "create-zip.sh" in case you're running a unix-based OS.

You might have luck asking @NerdyProjects ; he forked and improved on my work: https://github.com/NerdyProjects/MICGAIN-s5neolte

**Comment by ghost** [comment]
Fairphone is nice, but so expensive... different concepts of fairness I guess :eyes:  And sadly, eventually I will have to switch anyway in order to get recent security updates.

Thank you so much! I'll check that out, and also ask @NerdyProjects for help. And yes, I am running a unix-based OS :penguin: :)

**Comment by ghost** [comment]
Um there is no "issues" slider in @NerdyProjects fork, how can I actually contact them? :see_no_evil: 

Sorry I am the ultimate git hub noob :)

**Comment by NerdyProjects** [comment]
They are getting an email when you at-mention them :D But I am sorry that I cannot help with the actual issue. I just played around with MICGAIN when S5-neo was still a thing. I don't remember much of it - and honestly? The S5 neo is by current standards nearly unusable (unfortunately...) I am a happy Google Pixel 6a owner (using GrapheneOS)  now.

**Comment by ghost** [comment]
Oh that's a shame! Pixel is a worthy replacement I guess :muscle: 

If there was not the noise, and the security updates I would not care so much... 5G would be nice, but it's not mandatory for me. I am no power user I guess. And the fact that you are able to change the battery easily is so nice! This really annoys me about newer phones. I drop things, I lose things, and this is why I buy second hand... ;)

I wonder whether it's worth the risk installing this unofficial build: https://xdaforums.com/t/lineageos-19-1-for-s5neolte-sm-g903f-sm-g903w-and-sm-g903m.4599599/

This would at least fix the security updates issues, given the publisher is trustworthy :eyes:  And then, I can still try to fix the MICGAIN. What do you think?  Is your project likely to work with Android 12? :)

Thank you so much for your help!

**Comment by zeekoe** [comment]
You're welcome ;)
You can always download and extract the zip, and look for a mixer_paths like file. It might even all be fixed in Lineage 19.1, so my approach would be:
* Download the zip, look if there is a mixer_paths like file and if it is equal to the one in former releases.
* If so, install Lineage 19.1 and just try.
* If the sound is bad, install the zip and try again.

**Comment by ghost** [comment]
Thanks again :) Up to now, everything seems fine without installing the mod. I haven't had a lot of phone calls though. I'll do some further testing, and keep you posted :scientist:

**Comment by ghost** [comment]
The issue is solved using the new rom :ok_hand: 
Soo fellow people still using s5neo, there is hope :wink:

**Comment by zeekoe** [comment]
Great!
